name: Django Test

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ master, staging ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd backend_world
        python -m pip install --upgrade pip
        pip install pipenv
        python -m venv env-world
        source ./env-world/Scripts/activate.bat
        pipenv install
    - name: Run Tests
      run: |
        python manage.py test app.tests
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd backend_world
        python -m pip install --upgrade pip
        pip install pipenv
        python -m venv env-world
        source ./env-world/Scripts/activate.bat
        pipenv install
    - name: Run Tests
      run: |
        python manage.py test app.tests
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
